config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#show'
  
  resources :contact, only: [:index]
  resources :projet1, only: [:index]
  resources :projet2, only: [:index]
  resources :projet3, only: [:index]
  resources :projet4, only: [:index]
  resources :home, only: [:show]
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  	@video = Yt::Video.new id: 'kHUGYx0Xhec'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/projet1_controller.rb
class Projet1Controller < ApplicationController
  def index
  end
end

app/controllers/projet2_controller.rb
class Projet2Controller < ApplicationController
  def index
  end
end

app/controllers/projet3_controller.rb
class Projet3Controller < ApplicationController
  def index
  end
end

app/controllers/projet4_controller.rb
class Projet4Controller < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projet1_helper.rb
module Projet1Helper
end

app/helpers/projet2_helper.rb
module Projet2Helper
end

app/helpers/projet3_helper.rb
module Projet3Helper
end

app/helpers/projet4_helper.rb
module Projet4Helper
end

app/views/contact/index.html.erb
<div class="contact-page">
<div class="container">
	<br/>
	<h1 id="title" >Envie d'échanger?</h1>
	<br/><br/>
	<div class="row">
		<div class="col-lg-9 col-md-9 col-sm-9">
<form class="needs-validation" novalidate>
  <div class="form-row">
    <div class="col-md-4 mb-3">
      <label for="validationCustom">Nom / Prénom</label>
      <input type="text" class="form-control" id="validationCustom01" placeholder="Nom / Prénom" required>
      <div class="valid-feedback">
        So good!
      </div>
      <div class="invalid-feedback text-right">
          Votre nom et prénom sont nécéssaire
        </div>
    </div>
    <div class="col-md-4 mb-3">
      <label for="validationObject">Objet</label>
      <input type="text" class="form-control" id="validationObject" placeholder="Votre objet" required>
      <div class="valid-feedback">
        So good!
      </div>
      <div class="invalid-feedback text-right">
          Un objet est nécéssaire
        </div>
    </div>
    <div class="col-md-4 mb-3">
      <label for="validationEmail">Email</label>
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text" id="inputGroupPrepend">@</span>
        </div>
        <input type="email" class="form-control" id="validationCustomEmail" placeholder="Email" aria-describedby="inputGroupPrepend"  required>
        <div class="invalid-feedback text-right">
          Votre email valide est nécéssaire
        </div>
        <div class="valid-feedback text-right">
        I gotta you !
      </div>
      </div>
    </div> 
        <div class="col-lg-12 col-md-12 col-sm-12">
      <label for="validationCustom02">Message</label>
      <textarea type="text-area" class="form-control" id="validationCustom02" placeholder="Votre message" required></textarea>
      <div class="invalid-feedback text-right">
          Un message est nécéssaire
        </div>
    </div>
</div>
<br/>
	<div class="row">
	<div class="col">
		<button class="btn btn-outline-info" type="submit">Envoyer</button>
	</div>
</div>

</div>
	<div class="col-lg-3 col-md-3 col-sm-3 email-box">
		<div class="text-center text-box">
      		Ou<br/>directement<br/>par email: <br/><br/>
      		Cranyseng@gmail.com
      	</div>
    </div>
</form>
</div>
</div>
</div>
</div>


<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>

app/views/home/show.html.erb
<div class="hero">
	<%= image_tag "hero.jpg", class: "img-hero" %>
</div>

<div class="container">
	<div class="row justify-content-center">
		<div class="title-home col-6">
			<h1>Du graphisme à l'UX design -<br/>Sérany SENG</h1>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="intro d-flex justify-content-center dark-box">
			<div class="col-12">
				<h2 class="text-white">Every great design begins <br/> with an even better story.</h2>
				<p>Lorinda Mamo, Designer / Creative Director </p>
			</div>
		</div>
	</div>
</div>

<div class="container d-flex justify-content-center">
	<div class="vid-home">
		<% @video.embed_html %>
		<iframe src="http://www.youtube.com/embed/kHUGYx0Xhec" frameborder="0"></iframe>
	</div>
</div>
<div class="container d-flex justify-content-center">
	<div class="trait1"></div>
</div>
<div class="container d-flex justify-content-center">
	<div class="trait2"></div>
</div>
<div class="project-board">
	<div class="board">
		<div class="text-white d-flex justify-content-center">
			<h2 id="projet">Les projets</h2>
		</div>
		<div class="project d-flex justify-content-center">
			<div class="row d-flex justify-content-center">
				<div class="col-lg-3 col-md-6 col-sm-8" >
					<a href="<%= projet1_index_path %>" class="d-flex justify-content-center"><%= image_tag "eventlyon.png", class: "img-fluid" %></a>
					<p class="text-white text-center">Design system <br/>& Wireframe</p>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-8" >
					<a href="<%= projet2_index_path %>" class="d-flex justify-content-center"><%= image_tag "p2_chat.png", class: "img-fluid" %></a>
					<p class="text-white text-center">Du Back et du Front</p>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-8" >
					<a href="<%= projet3_index_path %>" class="d-flex justify-content-center"><%= image_tag "projet1.png", class: "img-fluid" %>
					</a>
					<p class="text-white text-center">Approche UX</p>
				</div>
			</div>
		</div>
		<div class="container d-flex justify-content-center">
			<div id="propos" class="trait3"></div>
		</div>
		<div class="container">
			<div class="propos">
				<h2 class="title-propos">A propos</h2>
				<div class="row">
					<div class="cadre col-lg-4 col-md-6 col-sm-10">
						<%= image_tag "portrait.jpg" %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="container">
	<div class="text-propos">
		<div class="row d-flex justify-content-end">
			<div class="col-lg-6 col-md-8 col-sm-12 text-white">
				<h3>Le commencement</h3>
					<p>En 2018, J'ai décidé de réaliser mes rêves. Vivre de se qui me passionnes et de mes créations. Après tout, est-ce vraiment vivre si les chemins qu'on emprunte nous indiffères?
					</p><br/>

					<h3>Du graphisme à L'UX design</h3>
					<p>Du genre curieux et passionné, j'ai fais de la psychologie, de l'antropologie et de l'art plastique à l'université en complément à mon cursus de graphiste print. J'ai longtemps cherché à meler les trois sans jamais vraiment trouver quoi. Et ce jusqu'à la découverte de l'UX design.</p><br/>

					<h3>De l'egocentrisme à l'user-centrisme</h3>
					<p>Pour illustrer cela, mes projets en sont la parfaite image. Ne plus faire des choses uniquements pour le beau mais pour l'usage. Tel est le défi que j'ai du me confronter. Car comme un gateau, c'est bien si il est beau mais c'est mieux si il est bon.</p>

					<div class="d-flex justify-content-end">
						<em>En savoir plus?</em>
					</div>
					<div class="d-flex justify-content-end">
						<%= link_to "Discutons !", contact_index_path, class: "btn btn-outline-info" %>
					</div>
			</div>
		</div>
	</div>
</div>

<div class="container d-flex justify-content-center">
	<div class="software">
		<h2 class="text-center text-black">Logiciels utilisés</h2>
		<br/><br/>
	<div class="row d-flex justify-content-center">
			<div class="col-lg-3 col-md-3 col-sm-4"><%= image_tag "photoshop.png" %></div>
			<div class="col-lg-3 col-md-3 col-sm-4"><%= image_tag "illustrator.png" %></div>
			<div class="col-lg-3 col-md-3 col-sm-4"><%= image_tag "indesign.png" %></div>
			<div class="col-lg-3 col-md-3 col-sm-4"><%= image_tag "premiere.png" %></div>
		</div>

		<div class="row d-flex justify-content-center">
			<div class="col-lg-3 col-md-3 col-sm-4"><%= image_tag "xd.png" %></div>
			<div class="col-lg-3 col-md-3 col-sm-4"><%= image_tag "invision.png" %></div>
			<div class="col-lg-3 col-md-3 col-sm-4"><%= image_tag "figma.png" %></div>
			<div class="col-lg-3 col-md-3 col-sm-4"><%= image_tag "sketch.png" %></div>
		</div>
	</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="animate.min.css">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark d-flex justify-content-center">
  <div class="nav-action">
    <ul class="nav-list">
      <li class="nav-element"><a href="<%= root_path %>"> Home </a></li>
      <li class="nav-element"><a href="#projet"> Projets </a></li>
      <li class="nav-element"><a href="#propos"> A propos </a></li>
      <li class="nav-element"><a href="<%= contact_index_path %>"> Contact </a></li>
    </ul>
  </div>
 </nav>
    <%= yield %>
    <footer>
      
    </footer>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/projet1/index.html.erb
<div class="project1">
	<div class="moodboard">
		<div class="img-moodboard">
			<%= image_tag "p1_moodboard.png", class: "img-fluid" %>
		<div class="container d-flex justify-content-center text-center">
			<div class="text-moodboard">
				<h1>Design system & Wireframe</h1>
				<p>« Il est impossible de tenir un design entre ses mains. Le design n’est pas une chose.<br/>C’est un processus. Un système. Une manière de penser ».</p>
				<em>Bob Gill, Designer</em>
			</div>
		</div>
		</div>
	</div>

	<div class="img-part1">
		<div class="container">
			<div class="row">
				<div class="col-lg-7 col-md-7">
					<div class="img-button">
						<%= image_tag "p1_button.svg", class: "img-fluid" %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="part1">
			<div class="row d-flex justify-content-end">
				<div class="col-lg-7 col-md-5 col-sm-6"> 
					<div class="p-1">
						<div class="p-1-text">
							<h2>Introduction à l'atomic design</h2>
							<p>Crée par Brad Frost, l’idée principale est d’<strong>organiser une site</strong> ou <strong>une application</strong>, non plus en tant qu'ensemble de pages mais plûtot comme <strong>un ensemble d'élèments</strong> qui selon comment ils s'associent entre eux définissent <strong>l'affichage et leurs rôles</strong>.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="img-part2">
			<div class="container">
				<div class="row d-flex justify-content-end">
					<div class="col-lg-8 col-md-8">
						<div class="img-text">
							<%= image_tag "p1_text.svg", class: "img-fluid" %>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="part2">
			<div class="row">
				<div class="col-lg-4 col-md-4"> 
					<div class="p-2">
						<div class="p-2-text">
							<h2>Hiérarchisation de l'information</h2>
							<p><strong>Définir</strong> des couleurs et des formats de texte selon <strong>leurs rôles</strong> et <strong>leurs importances</strong> permet <strong>suggérer en un clin d'oeil</strong> à l'utilisateur, les <strong>informations</strong> importantes et des <strong>appels à l'action</strong> clair.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="part3-all">
		<div class="img-part3">
			<div class="container d-flex justify-content-center">
				<div class="row">
					<div class="col-lg-12 col-md-12">
						<div class="img-text">
							<%= image_tag "p1_wireframe.png", class: "img-fluid" %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="part3">
				<div class="row d-flex justify-content-end">
					<div class="col-lg-4 col-md-4"> 
						<div class="p-3">
							<div class="p-3-text">
								<h2>Une identité</h2>
								<p>A partir d'une recherche graphique, d'une <strong>charte graphique</strong> et surtout de <strong>composants normés</strong>. Quelque soit le support ou la page internet. On <strong>reconnais</strong> instantanément la marque <strong>sans</strong> pour autant <strong>dénaturer</strong> leurs rôles</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
	
</div>

app/views/projet2/index.html.erb
<h1>Projet2#index</h1>
<p>Find me in app/views/projet2/index.html.erb</p>

app/views/projet3/index.html.erb
<h1>Projet3#index</h1>
<p>Find me in app/views/projet3/index.html.erb</p>

app/views/projet4/index.html.erb
<h1>Projet4#index</h1>
<p>Find me in app/views/projet4/index.html.erb</p>